### ISSUE TITLE
Your Repository 'Pull-Request-Pioneer' does not follow the values of Hacktober Event!

### ISSUE THREAD

**Issue by ashwinbekal** [SankshipthShetty/Pull-Request-Pioneer#57]
Heyy,
Since you have not added 'hacktoberfest' in your repository topic, the contributions made so far are not included or taken into consideration.

**Comment by SankshipthShetty** [comment]
Hey there! This repository was a part of the contributions for the hacktoberfest23 but as per the new guidelines of the hacktoberfest21 contributions such as adding a program file or making minor changes such as profile details are not being considered as a contribution for the hacktoberfest23. So this repository is just to practice how to send a pull request. Sorry for the inconveniene
